### ISSUE TITLE
Research which CI jobs should be made required

### ISSUE THREAD

**Issue by dzhavat** [Energinet-DataHub/greenforce-frontend#1005]
**Description:**
As pointed out by Bjarke Meier in Teams, it's possible to merge a PR even if some jobs have failed. On top of that, it looks like by setting a PR to "auto-merge", GitHub will merge it when all "required" steps have passed, even if other steps are still in progress. This can result in deploying a build that contains bugs. We need to find out which jobs should be made required before being allowed to merge a PR.

**NOTES:**
The solution should be heavily inspired by [opengeh-wholesale](https://github.com/Energinet-DataHub/opengeh-wholesale/tree/main/.github/workflows) made by The Outlaws.

**AC:**

- [ ] Research which CI jobs should be made required
- [ ] Make the desired job required

**Definition of Ready:**

- [ ] The issue is correctly estimated
- [ ] The issue is adequately described
- [ ] Possible dependencies are defined and aligned
- [ ] We have the necessary skills to complete this issue
- [ ] The issue can be completed withing 1 iteration
- [ ] The issue has acceptance criteria defined
- [ ] The issue has adequate Definition Of Done described

**Definition of Done:**

- [ ] Acceptance Criteria have been met
- [ ] The product has been demo’ed for relevant stakeholders
- [ ] Dependencies are handled
- [ ] The work has been documented
- [ ] The issue has been handed over and reviewed
- [ ] The PO has accepted the product

**Comment by ManBearTM** [comment]
Appears to be fixed in #1131, only thing missing was allow_merge not being required. This has been fixed.
