### ISSUE TITLE
UX for phase 1

### ISSUE THREAD

**Issue by mknic** [Energinet-DataHub/greenforce-frontend#1080]
### Description
Create a plan for UX work according to content in the phase 1 release.
The below subjects are bigger junks we need to break down into separate feature and user stories.
Create a plan for each feature on how to break down and get the features to fit into the product teams work eg. Mandalorian and Titans in first place.

### Subjects
User Journeys

Personaer

Brugeradministration
	- Snak med Søren og Kristian
	- Kan supporten kan tilgå alt data indenfor samme organisation?
	- UI/UX for at skifte mellem organisationer/aktører --> hvordan skal flowet se ud? Brugeren kan have forskelligerettigheder for de enkelte aktører/organisationer
	- Definer stakeholders

Onboarding new users/organisations
	- Snak med Søren og Kristian

Organisationer

Wholesale
	- Skære UX opgaver til at passe ind i de features der er defineret for wholesale
	- Definer stakeholders

Accessability

### AC
- [ ] Features are created for all subjects
- [ ] Stakeholders are identified for all topics

**Comment by frontend-specialisten** [comment]
@mknic @renehossle @PernilleChristiansen what should we do with this issue?
