### ISSUE TITLE
UI component library

### ISSUE THREAD

**Issue by mknic** [Energinet-DataHub/greenforce-frontend#1112]
Watt Figma library file should contain correct styles and components so it's easier to use the library when designing new screens.
Redundant and deprecated styles and components should be deleted or unpublished to reduce amount of styles and components.
We should be aligned with marketing on styles (we might already be aligned but don't know about the agreements)
Components in Figma library should be like components in Watt design system. 
Make components interactive

**Comment by frontend-specialisten** [comment]
New issues will be created
