### ISSUE TITLE
Update generators to standalone

### ISSUE THREAD

**Issue by frontend-specialisten** [Energinet-DataHub/greenforce-frontend#1141]
**Description:**
From Angular v. 15, standalone is no longer in the developer preview, so we should update our generators to be standalone by default.

**AC:**

- [ ] dh-library-generator should generate standalone components
- [x] watt-component-generator should generate standalone compoonents
- [x] use `nxConsole.generatorAllowlist` setting to define our own list of generators shown when clicking on the "generate" command in VS Code

**Comment by ManBearTM** [comment]
This has been fixed
