### ISSUE TITLE
From date in date range picker gets reset when used inside tabs

### ISSUE THREAD

**Issue by dzhavat** [Energinet-DataHub/greenforce-frontend#1175]
**Description:**
In a very specific scenario, where a date range picker is used in tabs, inside a drawer, the from date gets reset.

"/charges/prices" route has search results displayed in a table. Clicking a row, opens a drawer with tabs in it. Each tab has a date range picker which must display the same time period across all tabs. This is achieved by saving the selected time period in a service that is shared between all tabs.

![image.png](https://images.zenhubusercontent.com/612cb8944df0eb85278b93db/3b0e45c5-d246-4dff-a045-76fbb0cc7c23)

**The issue only appears when the dates are adjusted manually.**

To reproduce the issue:
- navigate to "/charges/prices" and make sure results are displayed in the table (e.g. by serving the app in mocked state)
- click on a row to open a drawer
- open the "Network" tab in DevTools (to observe outgoing requests)
- in the date range picker under the "Prices" tab, manually edit the "from" date (e.g. by changing the month)
- a new request is sent to the BFF with the new date
- click on the "Messages" tabs in the drawer
- a new request is sent again with the new date
- in the date range picker manually edit the "to" date (e.g. by changing the month)
- a new request is sent but this time the "from" date is reset back to the initial date when the drawer was first opened

![image.png](https://images.zenhubusercontent.com/612cb8944df0eb85278b93db/a6dd2863-0029-42c5-814e-217e6d0c0e7b)

**AC:**

- [ ] the date range picker values should stay consistent when used inside tabs

**Definition of Ready:**

- [ ] The issue is correctly estimated
- [ ] The issue is adequately described
- [ ] Possible dependencies are defined and aligned
- [ ] We have the necessary skills to complete this issue
- [ ] The issue can be completed withing 1 iteration
- [ ] The issue has acceptance criteria defined
- [ ] The issue has adequate Definition Of Done described

**Definition of Done:**

- [ ] Acceptance Criteria have been met
- [ ] The product has been demo’ed for relevant stakeholders
- [ ] Dependencies are handled
- [ ] The work has been documented
- [ ] The issue has been handed over and reviewed
- [ ] The PO has accepted the product

**Comment by frontend-specialisten** [comment]
@dzhavat Do you know if this is still an issue?

**Comment by dzhavat** [comment]
@frontend-specialisten Haven't looked at the bug since its creation but there hasn't been any functional changes to the date range picker either, so I think the bug is still there.
