### ISSUE TITLE
[UX / Frontend Alignment] Badge

### ISSUE THREAD

**Issue by frontend-specialisten** [Energinet-DataHub/greenforce-frontend#1188]
Large Badge er ikke I Storybook, men bruges i Expandable panel
Small Badge er ikke I Storybook, men bruges heller ikke?

**Comment by Lubbe91** [comment]
The badge size is already in the storybook, you can toggle it from input actions.

![image.png](https://images.zenhubusercontent.com/633c3b212ca0542c7aa8a750/c90210b0-c382-4583-8837-5b1978ae6ba1)
