### ISSUE TITLE
[UX / Frontend Alignment] Breadcrumbs

### ISSUE THREAD

**Issue by frontend-specialisten** [Energinet-DataHub/greenforce-frontend#1189]
Breadcrumbs skal have sort chevron i 16 px.
Kig også spacing mellem ikon og text
Skal også have hover effekt i primary-dark

**Comment by Lubbe91** [comment]
we don't have a `16px` version of our icons, it's a step between `M` & `S`, if we want a `16px` I suggest we bump the size of the `S` & `XS` to accommodate
