### ISSUE TITLE
Child metering point - processes and statusses

### ISSUE THREAD

**Issue by frontend-specialisten** [Energinet-DataHub/greenforce-frontend#120]
As Niels, grid company user, I want to get an overview of my child metering point processes and its statuses so that I can verify the latest updates on my metering point with my own system

### Acceptance Criteria 
- [ ] Show "process row" (process name, process id, creation date, cut-off date, process status, approval status as icons)
-  Exclamation icon = Rejected
-  Checkmark icon = Approved
- [ ] Sort processes by creation date as default (latest first)
- [ ] Show "Afvist"/"Rejected" on hover of exclamation-icon
- [ ] Show "Godkendt"/"Approved" on hover of checkmark-icon 
- [ ] Expand row and display "step rows" (step name, sender, receiver, creation date, cut-off-date, step status)
- [ ] Sort steps by creation date as default (oldest first)
- [ ] Show "step row" status with colors:
- Green = completed steps
- Red = rejected steps 
- Grey = pending steps

- [ ] Show only "DataHub" as name if "SenderEnergyParty" or "RecipientEnergyParty" is **5790001330583 (verify!)**
- [ ] Show both name and GLN number in parentheses if "SenderEnergyParty" or "RecipientEnergyParty" is other than DataHub 
- [ ] Show rejection message
- [ ] Open XML message **in new tab**
- [ ] Align with UX

➡️ &nbsp;[LINK TO PROTOTYPE](https://www.figma.com/proto/5lCd6Wq5bcDkOXIMgyLST6/DataHub-3.0?page-id=562%3A2395&node-id=665%3A8433&viewport=351%2C48%2C0.44&scaling=contain&starting-point-node-id=665%3A8433&show-proto-sidebar=1)

### Missing 
- [ ] Alignment with Batman
- [ ] Translations
- [ ] Align how dates should be formatted with business (reach out to Mogens)

### Processes in scope

- BRS-004 - Opret målepunkt
- BRS-006 - Vedligehold stamdata på målepunkt 
- BRS-008 - Tilslut målepunkt 

https://energinet.dk/El/DataHub/Dokumentation-og-regler

### Stakeholders

- Christian Meyer (PO, Batman)
- Dorthe og Maria (Support)

**Comment by mknic** [comment]
@dzhavat @frontend-specialisten should we close this? I presume it has been implemented?
