### ISSUE TITLE
Component: Tabs revamp

### ISSUE THREAD

**Issue by renehossle** [Energinet-DataHub/greenforce-frontend#1264]
Revamped tabs design, to support different use cases in a more user friendly way.

See the attached screenshots and Figma WATT.

To get the tab menu in the topbar, we need to make our own tab buttons which should be a a href tag element. Each tab links to a different subpage

**Comment by renehossle** [comment]
<iframe style="border: 1px solid rgba(0, 0, 0, 0.1);" width="800" height="450" src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2F4tVkjKm5fkIj61nx4XD3pA%2FDataHub-3.0%3Fnode-id%3D7178%253A77442%26t%3DSRiIQomxCes2evL8-1" allowfullscreen></iframe>

**Comment by renehossle** [comment]
![Screenshot 2022-12-30 at 09.17.57.png](https://images.zenhubusercontent.com/62274ef6bb2c7c0c7fd46c8c/4b64b00e-17ec-4545-ba3d-07ce5d75cba5)

**Comment by renehossle** [comment]
![Screenshot 2022-12-30 at 09.20.49.png](https://images.zenhubusercontent.com/62274ef6bb2c7c0c7fd46c8c/6059656d-b300-4048-8431-c6d031d15618)

**Comment by mimse** [comment]
@renehossle er vi ikke i mål med denne?

**Comment by ManBearTM** [comment]
This is probably done
