### ISSUE TITLE
Dropdown doesn't emit all selected values

### ISSUE THREAD

**Issue by dzhavat** [Energinet-DataHub/greenforce-frontend#1301]
When subscribing to `valueChanges` on a dropdown `FormControl`, the stream of values behaves differently depending on whether the user selects options directly from the list, or filters some options and selects from the filtered list.

1. Create dropdown with FormControl and subscribe to its valueChanges property. Log the emitted values
2. Select at least two items from the list
3. The selected values should be emitted from valueChanges
4. Open the dropdown again and filter the list
5. Select a single item from the list
6. Only one value is emitted from valueChanges. The expected output is to get all selected values (also the ones from step 1 to 3).

Possible solution: Look at `distinctUntilChanged` in `watt-dropdown.component.ts`

**Comment by frontend-specialisten** [comment]
@dzhavat, is this still an issue?

**Comment by dzhavat** [comment]
@frontend-specialisten No, don't think so. It seems like it works as expected now. Closing the issue :)
