### ISSUE TITLE
View Metering Point Processes and Statuses

### ISSUE THREAD

**Issue by stephaniegitha** [Energinet-DataHub/greenforce-frontend#145]
As Niels, grid company user, I want to get an overview of my metering point processes and its statuses so that I can verify the latest updates on my metering point with my own system

### Acceptance Criteria 
- [ ] Show "process row" (process name, process id, creation date, cut-off date, process status, approval status as icons)
-  Exclamation icon = Rejected
-  Checkmark icon = Approved
- [ ] Sort by creation date as default (latest first)
- [ ] Show "Afvist"/"Rejected" on hover of exclamation-icon
- [ ] Show "Godkendt"/"Approved" on hover of checkmark-icon   
- [ ] Align with UX

➡️ &nbsp;[LINK TO PROTOTYPE](https://www.figma.com/proto/5lCd6Wq5bcDkOXIMgyLST6/DataHub-3.0?page-id=562%3A2395&node-id=665%3A8433&viewport=351%2C48%2C0.44&scaling=contain&starting-point-node-id=665%3A8433&show-proto-sidebar=1)

### Missing 
- [ ] Alignment with Batman
- [ ] Translations
- [ ] Align how dates should be formatted with business (reach out to Mogens)

### Processes in scope

- BRS-004 - Opret målepunkt
- BRS-006 - Vedligehold stamdata på målepunkt 
- BRS-008 - Tilslut målepunkt 

https://energinet.dk/El/DataHub/Dokumentation-og-regler

### Stakeholders

- Christian Meyer (PO, Batman)
- Dorthe og Maria (Support)

**Comment by mknic** [comment]
@Christian-Meyer. This is the issue we have had in MD on processes and status overview in metering-point domain. Use some of it if it makes sense.
