### ISSUE TITLE
View Charge Links

### ISSUE THREAD

**Issue by stephaniegitha** [Energinet-DataHub/greenforce-frontend#146]
As Niels, grid company user, I want to view charge links on a metering point so that I can verify that it is consistent with the data in my own system

### Acceptance Criteria 
- [ ] Make sure only prices relevant for grid companies according to the comment posted below (prices should be filtered correctly when received from Volt): 
- 40000 
- 40010 
- 40020 
- 41000 
- 42000 
- 42001 
- 42002 
- 42030 
- 45012 
- 45013

- [ ] Show both active and inactive/historical prices in the same table (filtering out inactive prices is separated into [user story 206)](https://app.zenhub.com/workspaces/mighty-ducks-60ae1565be2dfe0017ff66b2/issues/energinet-datahub/green-energy-hub/206) 
- [ ] Highlight inactive/historicall prices (prices with an _end date_) with grey background color
- [ ] Sort all prices by start date (newest first) and group by price id 
- [ ] Show spinner when loading table (for each table) - replace with skeleton later
- [x] Show empty state if nothing to show (add empty state without icon to Design System?): [See prototype](https://www.figma.com/proto/5lCd6Wq5bcDkOXIMgyLST6/DataHub-3.0?page-id=562%3A2395&node-id=657%3A6011&viewport=351%2C48%2C0.44&scaling=contain&starting-point-node-id=572%3A2014&show-proto-sidebar=1)
- [ ] Following price elements should have the dollar icon in first column (elafgifter):
- EA-001
- EA-002
- EA-003
- EA-004
- EA-005 
- EA-006
- EA-007
- EA-008
- EA-009
- [ ] Show "Afgift"/"Tax" on hover of dollar icon   
- [ ] Align with UX 
- [ ] Align with IRS (SME, Volt)

➡️ &nbsp;[LINK TO PROTOTYPE](https://www.figma.com/proto/5lCd6Wq5bcDkOXIMgyLST6/DataHub-3.0?page-id=562%3A2395&node-id=642%3A4091&viewport=351%2C48%2C0.44&scaling=contain&starting-point-node-id=642%3A4091&show-proto-sidebar=1)

### Missing 
- [ ] Translations
- [ ] Align how dates should be formatted with business (reach out to Mogens)

**Comment by BjarkeMeier** [comment]
@mknic, what exactly does this mean "Sort all prices by start date (newest first) and group by price id"?  And what should be the order of the groups?

**Comment by frontend-specialisten** [comment]
@BjarkeMeier It means that the charge links in the UI should be sorted ascending by `startDate`, however if  the amount of charge links aren't huge this would preferably be done in the frontend as this would give the fastest user experience (when the sorting will be changeable later on).

In regarding of grouping this is only relavant when we have the historical data included.

**Comment by mknic** [comment]
Closed. Accept criterias not met will be covered in business-related features.
