### ISSUE TITLE
GUI Screen: Search Metering Point

### ISSUE THREAD

**Issue by mogensjuul** [Energinet-DataHub/greenforce-frontend#148]
## Problem Description
The user vil need the possibility to see the actual  data for a specific metering point for grid company user and support (Fas user)

### Benefit Hypothesis
In all cases where the is a doubt about the current status, the acutal situation can be clarified

## Acceptance criteria and must have scope
It must be possible to see the following data.
Master data - metering point domain
Charge links - Charge domain
Proces status -  metering point domain
History -  metering point domain

## Objectives and key results
Fullfilling a market criteria

## Leading Indicators
Supporting  the market actor

## Stakeholders
Describe who needs to be kept up-to-date about this feauture, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the feature.

## Timeline
What's the timeline for this feature, what resources are needed, and what might potentially block this from hitting the projected end date.

**Comment by mknic** [comment]
Non-related issues are moved to other features to be able to close this major feature.
