### ISSUE TITLE
404 Page 

### ISSUE THREAD

**Issue by stephaniegitha** [Energinet-DataHub/greenforce-frontend#150]
### Acceptance Criteria

- [x] Users who are **not** logged in should be redirected to login page
- [ ] Users who are logged in should see an empty state: [See prototype](https://www.figma.com/proto/5lCd6Wq5bcDkOXIMgyLST6/DataHub-3.0?page-id=562%3A2395&node-id=772%3A5599&viewport=241%2C48%2C0.15&scaling=contain&starting-point-node-id=772%3A5599&show-proto-sidebar=1)

**Comment by mknic** [comment]
Closed. We are redirecting to search metering point page as we don't have any navigation at the moment.
