### ISSUE TITLE
GitGuardian has uncovered 2 secrets following the scan of your pull request

### ISSUE THREAD

**Issue by frontend-specialisten** [Energinet-DataHub/greenforce-frontend#1541]
`libs/dh/shared/feature-authorization/src/lib/permission.service.spec.ts` and `libs/dh/shared/feature-authorization/src/lib/permission.service.spec.ts` triggers GitGuardian. This is a properly false-positive, so we should have these files ignored or change the specs, so the secrets aren't triggering GitGuardian. 

![image.png](https://images.zenhubusercontent.com/612cbcaa9fd6401e03dda309/2da2113c-bf07-4819-aed9-f0032cd0157b)

**Comment by ManBearTM** [comment]
This has been fixed
