### ISSUE TITLE
Search input that can expand

### ISSUE THREAD

**Issue by MadsThy** [Energinet-DataHub/greenforce-frontend#1765]
Note:

Replace "Bestilt af" free text search with new global search/filtering option.

See video below for functionality.

**Comment by renehossle** [comment]
https://images.zenhubusercontent.com/399470875/0372ebfb-9724-4d57-afd5-b9dda7989f6b/screen_recording_2023_06_15_at_11_06_57.mov

**Comment by renehossle** [comment]
![Screenshot 2023-06-15 at 12.27.36.png](https://images.zenhubusercontent.com/62274ef6bb2c7c0c7fd46c8c/fe8df02f-23ad-41e7-982e-765bb018060d)

300ms, bezier-curve: 0.75, 0, 0.25, 1
