### ISSUE TITLE
Move start calculation functionality into search batch page

### ISSUE THREAD

**Issue by ManBearTM** [Energinet-DataHub/greenforce-frontend#1796]
### Synopsis
As a user
I want to be able to start a batch from the batch overview page
So that I don't have to navigate between two pages

### AC
- [ ] A new batch can be created from a modal on the batch (calculations?) page
- [ ] UX 
- [x] #1880
- [x] #1879

**Comment by MadsBloendAndersen** [comment]
@renehossle could you maybe paste the UX for this issue, I cant find it.
