### ISSUE TITLE
Replace deprecated `print-affected` Nx command

### ISSUE THREAD

**Issue by dzhavat** [Energinet-DataHub/greenforce-frontend#2187]
The `print-affected` Nx command is [deprecated](https://nx.dev/nx-api/nx/documents/print-affected) and scheduled for removal in v18.

Replace it with `nx show` [command](https://nx.dev/nx-api/nx/documents/show).

**Comment by ManBearTM** [comment]
Fixed in https://github.com/Energinet-DataHub/greenforce-frontend/commit/0157890e58f4017052e4935891333190ae3ae31e
