### ISSUE TITLE
[Spike] investigate how multiple rejections in process overview is done in GUI

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/greenforce-frontend#297]
It is possible that multiple error messages are shown here?

![image](https://user-images.githubusercontent.com/72008712/149948632-4a6a0670-f1e9-4356-be39-135bf76aa389.png)

_Prototype can be found in figma under: Målepunkt - Processer_

**Comment by MadsBloendAndersen** [comment]
Hey @Christian-Meyer. Are you able to investigate whether or not it becomes relevant to show more error messages in the gui, as shown in the prototype (See description).

**Comment by Christian-Meyer** [comment]
@MadsBloendAndersen I have spoken to Alexander and UX will make a prototype of it. It is still a requirement.

**Comment by frontend-specialisten** [comment]
Just talked with @jonaseilsoe and we are going with following solution for now (this can also be found in figma):
![image](https://user-images.githubusercontent.com/86852536/150989914-9bcaf1c8-8e1d-4887-9271-344f1f6a5acc.png)

**Comment by MadsBloendAndersen** [comment]
@frontend-specialisten + @jonaseilsoe looks good!
