### ISSUE TITLE
Setup code coverage using CodeCov

### ISSUE THREAD

**Issue by dzhavat** [Energinet-DataHub/greenforce-frontend#314]
SonarCloud can track and report code coverage but it is currently not working correctly.

In order to set it up correctly, we need to:

- [ ] Generate code coverage reports when tests run in CI pipeline
- [ ] Concatenate all reports to a single LCOV file
- [ ] Point SonarCloud to that file 

Tech notes 
- https://docs.sonarcloud.io/enriching/test-coverage-and-execution/
- https://github.com/ngworker/lumberjack/blob/main/sonar-project.properties
- https://github.com/ngworker/lumberjack/blob/main/tools/scripts/generate-test-coverage-reports.mjs

**Comment by MadsBloendAndersen** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Joules-5fd22a1a59e4740018f5ab5a/issues/Energinet-DataHub/greenforce-frontend/314?planning-poker) with ZenHub @dzhavat @frontend-specialisten

**Comment by dzhavat** [comment]
@MadsBloendAndersen @frontend-specialisten I have given my estimate :)
