### ISSUE TITLE
Disabled buttons can be clicked 

### ISSUE THREAD

**Issue by dzhavat** [Energinet-DataHub/greenforce-frontend#328]
Disabled buttons in Watt Design System emit click events in Edge/Chrome/Safari, not in Firefox.

https://images.zenhubusercontent.com/399470875/65d1122f-ff28-4c3a-89eb-dcec8d1e4101/fkcn7hdwqaear8b.mp4

Possible solution:

- Add `pointer-events: none` to the button if it's disabled. [StackBlitz example](https://stackblitz.com/edit/angular-nh42jz-bobouf?file=src%2Fapp%2Fmaterial-button%2Fmaterial-button.component.ts)

**Comment by mknic** [comment]
Replaced by an issue in Mighty Ducks.
