### ISSUE TITLE
Deployment of custom login and sign up layout

### ISSUE THREAD

**Issue by mknic** [Energinet-DataHub/greenforce-frontend#340]
Currently the custom login layout is uploaded manually to blob storage which is not ideal. 
We should create a more formalized way of updating the custom login layout. 

Maybe a custom static application with a webpack config or something? 

Currently B2C is pointing at `https://stordesignendku.z6.web.core.windows.net/login-unified.html`
This should be changed to the correct environment as well.
Due the fact that we're now hosted at a static web app and not a storage account, please take into account that we can't just upload and test it manually. We need to find a solution for this as well (also how to handle changes, when we're live).
Please also note that CORS has been setup at the storage account for each b2c environment [here](https://portal.azure.com/#@energinet.onmicrosoft.com/resource/subscriptions/d252b8da-1db8-44f7-bd6e-8010cc01382b/resourceGroups/rg-DataHub-GUI-U/providers/Microsoft.Storage/storageAccounts/stordesignendku/corsblade)

And the file is located here in the repository:
`libs/dh/shared/assets/src/assets/login-page/login-unified.html` 

**Acceptance criteria:**
- [ ] Custom login layout is deployed in the build pipeline like the rest of our applications
- [ ] Adjust B2C to point at the correct environments (see getting-started.md) - Reach out to Daniel (Mighty Ducks)
- [ ] Make it possible to test pages locally

**Tech notes:**
- Try to reuse some of the styling (colors, sizes etc.)

**Comment by ManBearTM** [comment]
Closing, this is now owned by Racoons.
