### ISSUE TITLE
Incorrect text in the Mailbekræftelseskode 

### ISSUE THREAD

**Issue by khatozen** [Energinet-DataHub/greenforce-frontend#349]
In the notification mail “Mailbekræftelseskode” that sends from DataHub to the new created user, there is a link to a web address instead of the sender name (Datahub), see the screenshot bellow:

![image.png](https://images.zenhubusercontent.com/6110f1589f04be24392a986f/4d7badec-f0b9-4933-a1a0-b9a6f51daeb6)

**Comment by frontend-specialisten** [comment]
@mknic If this is still relevant, please move this to the outlaws.
