### ISSUE TITLE
[BUG] Sidebar disappears when Esc button is pressed

### ISSUE THREAD

**Issue by dzhavat** [Energinet-DataHub/greenforce-frontend#354]
### Current Behavior

On large screens, the sidebar disappears when Esc button is pressed

### Expected behavior

On large screens, it shouldn't be possible to dismiss/close the sidebar. It must be always visible.

### How to reproduce

- Open the DataHub app
- Click anywhere in the sidebar
- Press Esc button

### Additional context/screenshots

It should still be possible to close the sidebar by pressing the Esc button on small screens.

**Comment by MadsThy** [comment]
The bug was fixed in #494 . It was a missing disableClose property on the sidenav that needed to be put in, to ignore close commands when on large screens.
