### ISSUE TITLE
Align colors with latest changes from UX

### ISSUE THREAD

**Issue by frontend-specialisten** [Energinet-DataHub/greenforce-frontend#356]
Justering af farver således de opfylder vores krav omkring web-tilgængelighed (øge læsbarheden).
Undgå forvirring mellem UX og udviklere da implementering pt. er ude af sync.   

**Acceptance criteria:**

- [x] Global styles of colors are aligned with figma
- [x] Add primary-light
- [x] Add secondary colors
- [x] Add data visualization colors
- [x] Remove focus colors
- [x] Storybook showcase / docs of colors should look like figma

**Technical notes:**
- Emphasis has it's own task https://github.com/Energinet-DataHub/greenforce-frontend/issues/357
- State colors should still be named danger, warning, success and info. Figma will be changed to reflect this.

**Comment by TRK555** [comment]
Status: Dzhavat skriver at de ikke kommer til at arbejde på denne opgave i nuværende PI og at næste PI planning er 2. maj.
