### ISSUE TITLE
Text colors (emphasis) and text colors based on context

### ISSUE THREAD

**Issue by frontend-specialisten** [Energinet-DataHub/greenforce-frontend#357]
In Figma, Storybook, and `@energinet-datahub/watt`.

Emphasized text. for example global style, class, and/or mixin.

Context-based colors, for example:
- Text color on top of primary color background
- Text color on top of secondary color background

Opacity for *interactive text*?

Feature environment for this is located at:
https://eo-u-textemphasisan.westeurope.cloudapp.azure.com/origin-of-energy

**Comment by TRK555** [comment]
Status: Dzhavat skriver at de ikke kommer til at arbejde på denne opgave i nuværende PI og at næste PI planning er 2. maj.
