### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by frontend-specialisten** [Energinet-DataHub/greenforce-frontend#399]
As a user I would like to get notified with a message, so that I can be informed with relevant information.

![image.png](https://images.zenhubusercontent.com/612cbcaa9fd6401e03dda309/705ec43b-5b20-4e0b-9761-d5f495b8200f)

**Acceptance criteria:**
- [ ] Component can be tested in Watt Design System Storybook.  
- [ ] Component can be used in sketches from Watt Design System in Figma library.
- [ ] There should be displayed an icon indicating the type of notification: Info, Warning, Danger, Success
- [ ] There should be an optional headline.
- [ ] There should be a text.
- [ ] There should be a dark and light theme.
- [ ] It should be optional to display a close icon.
- [ ] It should be possible to have multiple notifications in a list.

**Sketches:**
Notification:
https://www.figma.com/file/fwEDQkgEcpwfUojXl0EIC5/Watt-Design-System?node-id=260%3A4805

Landing Page 0.1 - Large Screen:
https://www.figma.com/file/GvFueW0dNEAF4vUBonZqtv/Energioprindelse.dk?node-id=1086%3A4476

Landing Page 0.1 - Small Screen:
https://www.figma.com/file/GvFueW0dNEAF4vUBonZqtv/Energioprindelse.dk?node-id=658%3A4536

**Technical notes:**
Currently we have a component in storybook called validation message

**Solution plan (Developers)**
Frontend
- [ ] Should support content projection
- [ ] Should support neutral background
- [ ] Should support drop shadow

Backend
- [ ] step 1
- [ ] step 2

**Review checklist**
- [ ] Code review
- [ ] Definition of Done
- [ ] Accepted by watt team (demo)

**Comment by mknic** [comment]
Not applicable
