### ISSUE TITLE
Feature flags based on environment

### ISSUE THREAD

**Issue by dzhavat** [Energinet-DataHub/greenforce-frontend#406]
**AC**

- [ ] Feature flag is configurable in each environment

**When configuration file for environment has been created in `greenforce-frontend`** this configuration should be replaced by [workflow](https://github.com/Energinet-DataHub/dh3-environments/blob/main/.github/workflows/dh-ui-frontend-stage-deployment.yml). Use `ENVIRONMENT` and `ENVIRONMENT_INSTANCE` (b-002 = itlev).

**Comment by mknic** [comment]
Relates to: https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/356
