### ISSUE TITLE
Documentation for feature flags

### ISSUE THREAD

**Issue by dzhavat** [Energinet-DataHub/greenforce-frontend#408]
**AC**

- [ ] Document feature flag service
- [ ] Document feature flag directive
- [ ] Document feature flag configuration and environment overwrites
- [ ] Notify feature teams

**Comment by mknic** [comment]
@dzhavat @ManBearTM @frontend-specialisten the wholesale domain would be the place we start to implement the feature flag mechanism and I think that experience together with them would provide good feedback to our documentation. Nevertheless, it's nice having this issue and I definitely agree with creating documentation before we announce the readiness of this feature.
