### ISSUE TITLE
Choose monospaced font

### ISSUE THREAD

**Issue by mknic** [Energinet-DataHub/greenforce-frontend#425]
**Description**
Decide if we are allowed to choose monospaced font.

**AC**
- [x] Decide and document if we can use a monospaced font
- [x] Agreement in frontend group if we are allowed to change font
- [x] Align with Fenris

**Comment by renehossle** [comment]
Font is Droid Sans Mono (Open Sans is build on Droid Sans)

it has been run through Sofie Kragh (SKG kommunikation og kultur) and she is aware that we are using this.
