### ISSUE TITLE
Sort stories in sidebar

### ISSUE THREAD

**Issue by frontend-specialisten** [Energinet-DataHub/greenforce-frontend#520]
Currently our `overview` pages aren't sorted as the first stories in the sidebar under the components. 
Storybook only support sorting of a navigation level of 2, otherwise you need to apply your own sorting function. Luckily we are not the only ones who had this problem, so hopefully this can be fixed by taking following examples:

https://github.com/storybookjs/storybook/issues/548

![image.png](https://images.zenhubusercontent.com/612cbcaa9fd6401e03dda309/40470ffa-0e20-4878-8c04-b2a783ba87c9)

**Comment by mknic** [comment]
Not applicable

**Comment by joriswitteman** [comment]
What does not applicable mean?
