### ISSUE TITLE
Selection list?

### ISSUE THREAD

**Issue by frontend-specialisten** [Energinet-DataHub/greenforce-frontend#556]
Currently titans is using selection list of material. However this feature haven't been through UX so is this component something we want in the design system or can we provide them with something else UX'wise? 

https://material.angular.io/components/list/overview#selection-lists

![image.png](https://images.zenhubusercontent.com/612cbcaa9fd6401e03dda309/44a78fd9-bdcd-4602-87c7-55769bf100a9)

**Comment by mknic** [comment]
Not applicable
