### ISSUE TITLE
Button styling (outline when active, makes button overflow)

### ISSUE THREAD

**Issue by frontend-specialisten** [Energinet-DataHub/greenforce-frontend#736]
Example:
![image.png](https://images.zenhubusercontent.com/612cbcaa9fd6401e03dda309/1718548e-efda-4f73-b0c8-d98a7cf5f958)

**Please note this is not only an issue in the drawer component, the problem has been located in other places in DataHub application as well**

**Comment by ManBearTM** [comment]
Confirmed to be fixed by #671
