### ISSUE TITLE
Date / daterange "stepper"

### ISSUE THREAD

**Issue by frontend-specialisten** [Energinet-DataHub/greenforce-frontend#810]
### Version 0.1

- Toggle between day/whole period
- Keyboard shortcuts left/right?

### Version 0.2

 ![image.png](https://images.zenhubusercontent.com/612cbcaa9fd6401e03dda309/9dd8dcd9-d34a-49eb-8f83-b1b79b71988b)

**Acceptance Criteria**
- [ ] Implement stepper for date-range input 
- [ ] Steps should be configurable (day, month, year)
- [ ] Should be showcased and documented in storybook
- [ ] Change of "step" overrides existing input and uses a current day, week, month etc. 
- [ ] If input becomes "dirty", stepper should be disabled, can be enabled by clicking on one of the "steps" again. 
 
**Tech notes**
Should it be an existing date-range component with `steps=true` or it's own component?

**Comment by frontend-specialisten** [comment]
@renehossle @PernilleChristiansen is this component used in the near future?

**Comment by PernilleChristiansen** [comment]
@frontend-specialisten Not that I know of - I think @renehossle knows
