### ISSUE TITLE
Datepicker placeholder doesn't update when DH language is changed

### ISSUE THREAD

**Issue by dzhavat** [Energinet-DataHub/greenforce-frontend#896]
**Description:**
Placeholder in datepicker stays `dd-mm-åååå` even after language in DataHub is changed to `EN`.
The date format should be `dd-mm-åååå` when the language is set to `DA` and `dd-mm-yyyy` when set to `EN`.

**AC:**
- [ ] Placeholder value should reflect the selected language

**Note**
A similar solution is used for `copy-to-clipboard` feature.

**Comment by Lubbe91** [comment]
Seems like this one goes a little deeper than expected.

The inputs are using a masking service that needs to be configured as well.

The English format is incorrect, but I stopped further development until it's decided how to proceed

https://images.zenhubusercontent.com/399470875/ef173eb3-566c-4429-b91d-53f50de45755/2023_01_30_08_46_30.mp4
