### ISSUE TITLE
BUG: Multi-line table header cells

### ISSUE THREAD

**Issue by frontend-specialisten** [Energinet-DataHub/greenforce-frontend#983]
If some of the table header cells are multi-line, the styling breaks as shown below. This can be fixed by making the header cells stretch, but we need to ensure this doesn't break something else. 

![image.png](https://images.zenhubusercontent.com/612cbcaa9fd6401e03dda309/87d70f72-baad-41d3-a1e1-f40cca6fb288)

**Comment by frontend-specialisten** [comment]
@ManBearTM check if we can close this.

**Comment by frontend-specialisten** [comment]
@ManBearTM check if we can close this.

**Comment by ManBearTM** [comment]
Fixed in watt-table, which should be used over mat-table going forward.
